// Seeded quotes grouped by mood for fast O(1) access
const quotesByMood = {
  "sad": [
    { "quote": "The wound is the place where the Light enters you.", "author": "Rumi" },
    { "quote": "Tears come from the heart and not from the brain.", "author": "Leonardo da Vinci" },
    { "quote": "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.", "author": "Christopher Morley" },
    { "quote": "Sadness flies away on the wings of time.", "author": "Jean de La Fontaine" },
    { "quote": "Every man has his secret sorrows which the world knows not.", "author": "Henry Wadsworth Longfellow" },
    { "quote": "Even a happy life cannot be without a measure of darkness.", "author": "Carl Jung" },
    { "quote": "The walls we build around us to keep sadness out also keeps out the joy.", "author": "Jim Rohn" },
    { "quote": "When you are sorrowful, look again in your heart.", "author": "Khalil Gibran" },
    { "quote": "To have felt too much is to end in feeling nothing.", "author": "Dorothy Thompson" },
    { "quote": "Tears shed for another person are not a sign of weakness. They are a sign of a pure heart.", "author": "José N. Harris" },
    { "quote": "Grief is the price we pay for love.", "author": "Queen Elizabeth II" },
    { "quote": "There is no despair so absolute as that which comes with the first moments of our first great sorrow.", "author": "George Eliot" },
    { "quote": "Sorrow is one of the vibrations that prove the fact of living.", "author": "Antoine de Saint-Exupéry" },
    { "quote": "The good times of today are the sad thoughts of tomorrow.", "author": "Bob Marley" },
    { "quote": "It's sad when someone you know becomes someone you knew.", "author": "Henry Rollins" },
    { "quote": "Every human walks around with a certain kind of sadness.", "author": "Brad Pitt" },
    { "quote": "Behind every sweet smile, there is a bitter sadness that no one can ever see and feel.", "author": "Tupac Shakur" },
    { "quote": "The tragedy of life is not so much what men suffer, but rather what they miss.", "author": "Thomas Carlyle" },
    { "quote": "The soul would have no rainbow if the eyes had no tears.", "author": "Native American Proverb" },
    { "quote": "Sometimes we get sad because we’ve been strong for too long.", "author": "Unknown" }
  ],
  "troubled": [
    { "quote": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein" },
    { "quote": "Do not let what you cannot do interfere with what you can do.", "author": "John Wooden" },
    { "quote": "Turn your wounds into wisdom.", "author": "Oprah Winfrey" },
    { "quote": "If you’re going through hell, keep going.", "author": "Winston Churchill" },
    { "quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson" },
    { "quote": "Out of difficulties grow miracles.", "author": "Jean de La Bruyère" },
    { "quote": "Problems are not stop signs, they are guidelines.", "author": "Robert H. Schuller" },
    { "quote": "We must embrace pain and burn it as fuel for our journey.", "author": "Kenji Miyazawa" },
    { "quote": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi" },
    { "quote": "The best way out is always through.", "author": "Robert Frost" },
    { "quote": "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.", "author": "Napoleon Hill" },
    { "quote": "There is a crack in everything, that’s how the light gets in.", "author": "Leonard Cohen" },
    { "quote": "Storms make trees take deeper roots.", "author": "Dolly Parton" },
    { "quote": "Even the darkest night will end and the sun will rise.", "author": "Victor Hugo" },
    { "quote": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela" },
    { "quote": "Let your hopes, not your hurts, shape your future.", "author": "Robert H. Schuller" },
    { "quote": "Hard times may have held you down, but they will not last forever.", "author": "Joel Osteen" },
    { "quote": "Strength doesn’t come from what you can do. It comes from overcoming the things you thought you couldn’t.", "author": "Rikki Rogers" },
    { "quote": "Life isn’t about waiting for the storm to pass. It’s about learning how to dance in the rain.", "author": "Vivian Greene" },
    { "quote": "You may not control all the events that happen to you, but you can decide not to be reduced by them.", "author": "Maya Angelou" }
  ],
    "neutral": [
    { "quote": "Act without expectation.", "author": "Lao Tzu" },
    { "quote": "Don't believe everything you think.", "author": "Byron Katie" },
    { "quote": "Let it be.", "author": "John Lennon" },
    { "quote": "Silence is sometimes the best answer.", "author": "Dalai Lama" },
    { "quote": "The only way to make sense out of change is to plunge into it.", "author": "Alan Watts" },
    { "quote": "Do nothing, and nothing is left undone.", "author": "Lao Tzu" },
    { "quote": "You are the sky. Everything else – it's just the weather.", "author": "Pema Chödrön" },
    { "quote": "Be — don’t try to become.", "author": "Osho" },
    { "quote": "Flow with whatever may happen and let your mind be free.", "author": "Zhuangzi" },
    { "quote": "Sometimes it’s better to remain silent and smile.", "author": "Unknown" },
    { "quote": "Life is really simple, but we insist on making it complicated.", "author": "Confucius" },
    { "quote": "A journey of a thousand miles begins with a single step.", "author": "Lao Tzu" },
    { "quote": "To the mind that is still, the whole universe surrenders.", "author": "Lao Tzu" },
    { "quote": "Accept what is, let go of what was, and have faith in what will be.", "author": "Sonia Ricotti" },
    { "quote": "Simplicity is the ultimate sophistication.", "author": "Leonardo da Vinci" },
    { "quote": "He who is contented is rich.", "author": "Lao Tzu" },
    { "quote": "Nothing happens unless first a dream.", "author": "Carl Sandburg" },
    { "quote": "Nature does not hurry, yet everything is accomplished.", "author": "Lao Tzu" },
    { "quote": "When you realize nothing is lacking, the whole world belongs to you.", "author": "Lao Tzu" },
    { "quote": "The mind is everything. What you think you become.", "author": "Buddha" }
  ],
  "happy": [
    { "quote": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama" },
    { "quote": "The purpose of our lives is to be happy.", "author": "Dalai Lama" },
    { "quote": "Count your age by friends, not years. Count your life by smiles, not tears.", "author": "John Lennon" },
    { "quote": "Let us be grateful to the people who make us happy.", "author": "Marcel Proust" },
    { "quote": "For every minute you are angry you lose sixty seconds of happiness.", "author": "Ralph Waldo Emerson" },
    { "quote": "The most wasted of all days is one without laughter.", "author": "Nicolas Chamfort" },
    { "quote": "Happiness depends upon ourselves.", "author": "Aristotle" },
    { "quote": "Do more things that make you forget to check your phone.", "author": "Unknown" },
    { "quote": "The best way to cheer yourself is to try to cheer someone else up.", "author": "Mark Twain" },
    { "quote": "Joy is not in things; it is in us.", "author": "Richard Wagner" },
    { "quote": "Laugh as much as you breathe, love as long as you live.", "author": "Johnny Depp" },
    { "quote": "Happiness is letting go of what you think your life is supposed to look like.", "author": "Mandy Hale" },
    { "quote": "Smile, it's free therapy.", "author": "Douglas Horton" },
    { "quote": "Being happy never goes out of style.", "author": "Lilly Pulitzer" },
    { "quote": "Happiness is a warm puppy.", "author": "Charles M. Schulz" },
    { "quote": "Success is getting what you want. Happiness is wanting what you get.", "author": "Dale Carnegie" },
    { "quote": "The best things in life are free. The second-best are very expensive.", "author": "Coco Chanel" },
    { "quote": "Happiness held is the seed; happiness shared is the flower.", "author": "John Harrigan" },
    { "quote": "Doing what you like is freedom. Liking what you do is happiness.", "author": "Frank Tyger" },
    { "quote": "Take time to make your soul happy.", "author": "Unknown" }
  ],
  "excited": [
    { "quote": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt" },
    { "quote": "Life is either a daring adventure or nothing at all.", "author": "Helen Keller" },
    { "quote": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt" },
    { "quote": "Adventure is worthwhile.", "author": "Aesop" },
    { "quote": "Don’t count the days, make the days count.", "author": "Muhammad Ali" },
    { "quote": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky" },
    { "quote": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt" },
    { "quote": "Just do it.", "author": "Phil Knight" },
    { "quote": "Leap and the net will appear.", "author": "John Burroughs" },
    { "quote": "Once in a while it really hits people that they don’t have to experience the world in the way they have been told.", "author": "Alan Keightley" },
    { "quote": "Dream big and dare to fail.", "author": "Norman Vaughan" },
    { "quote": "Live life with no excuses, travel with no regret.", "author": "Oscar Wilde" },
    { "quote": "The power of imagination makes us infinite.", "author": "John Muir" },
    { "quote": "Today is your opportunity to build the tomorrow you want.", "author": "Ken Poirot" },
    { "quote": "Whatever you do, or dream you can, begin it.", "author": "Johann Wolfgang von Goethe" },
    { "quote": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer" },
    { "quote": "Be fearless in the pursuit of what sets your soul on fire.", "author": "Jennifer Lee" },
    { "quote": "Don't wait. The time will never be just right.", "author": "Napoleon Hill" },
    { "quote": "If you want to lift yourself up, lift up someone else.", "author": "Booker T. Washington" },
    { "quote": "Live every moment, laugh every day, love beyond words.", "author": "Unknown" }
  ]
};

module.exports = quotesByMood;
